/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 25-mai-2016 11:54:51 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `backups` CASCADE
;

DROP TABLE IF EXISTS `chunks` CASCADE
;

DROP TABLE IF EXISTS `files` CASCADE
;

DROP TABLE IF EXISTS `peers` CASCADE
;

/* Create Tables */

CREATE TABLE `backups`
(
	`peer` CHAR(36) NOT NULL,
	`file_chunk` INT UNSIGNED NOT NULL,
	CONSTRAINT `PK_file_chunk` PRIMARY KEY (`peer` ASC, `file_chunk` ASC)
)

;

CREATE TABLE `chunks`
(
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`file` CHAR(36) NOT NULL,
	`chunk` INT NOT NULL,
	`replication` INT NOT NULL DEFAULT 0,
	CONSTRAINT `PK_chunks` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `files`
(
	`uuid` CHAR(36) NOT NULL,
	`peer` CHAR(36) NOT NULL,
	`name` VARCHAR(256) NOT NULL,
	CONSTRAINT `PK_files` PRIMARY KEY (`uuid` ASC)
)

;

CREATE TABLE `peers`
(
	`serial_number` CHAR(36) NOT NULL,
	CONSTRAINT `PK_peers` PRIMARY KEY (`serial_number` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `backups` 
 ADD INDEX `IXFK_backups_chunks` (`file_chunk` ASC)
;

ALTER TABLE `backups` 
 ADD INDEX `IXFK_backups_peers` (`peer` ASC)
;

ALTER TABLE `chunks` 
 ADD CONSTRAINT `UK_file_chunk` UNIQUE (`chunk` ASC, `file` ASC)
;

ALTER TABLE `chunks` 
 ADD INDEX `IXFK_chunks_files` (`file` ASC)
;

ALTER TABLE `files` 
 ADD INDEX `IXFK_files_peers` (`peer` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `backups` 
 ADD CONSTRAINT `FK_backups_chunks`
	FOREIGN KEY (`file_chunk`) REFERENCES `chunks` (`id`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `backups` 
 ADD CONSTRAINT `FK_backups_peers`
	FOREIGN KEY (`peer`) REFERENCES `peers` (`serial_number`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `chunks` 
 ADD CONSTRAINT `FK_chunks_files`
	FOREIGN KEY (`file`) REFERENCES `files` (`uuid`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `files` 
 ADD CONSTRAINT `FK_files_peers`
	FOREIGN KEY (`peer`) REFERENCES `peers` (`serial_number`) ON DELETE Restrict ON UPDATE Cascade
;

SET FOREIGN_KEY_CHECKS=1 
;
